# Generated by Django 2.0.3 on 2018-03-12 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180312_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='shipper',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.Shipper'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
