# Generated by Django 2.0.3 on 2018-03-12 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180312_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='shipper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sh_deliveries', to='core.Shipper'),
        ),
    ]
