# Generated by Django 2.0.3 on 2018-03-14 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180312_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prealert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking', models.CharField(max_length=100)),
                ('delivery_date', models.DateField()),
                ('provider', models.CharField(help_text='Ex: Amazon, Ebay, etc.', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('content', models.TextField()),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Shipper')),
            ],
        ),
    ]
